### ISSUE TITLE
Refactor types into types.rs

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-node#16]
The types in pallet_chocolate make it a bit difficult to move around easily,
a simple move from lib.rs would do good, leaving only the needed type aliases.

This entails simply moving the [project](https://github.com/chocolatenetwork/chocolate-node/blob/master/pallets/chocolate/src/lib.rs#L202) struct and its dependencies.

**Comment by islami00** [comment]
Nice, I will have seen them and will use them as a guide while working on the refactor.
This implies we'll be having a primitives crate right?

**Comment by SHA888** [comment]
I think we need it
