### ISSUE TITLE
Change default for proposal status enum to Accepted

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-node#29]
**Motivation**

Currently, every review or project goes into a proposed stage before the `accept_review` extrinsic is called. Since we don't really have a governance system in place, it would be more user friendly to have all content start off as accepted, and then have it switch to other states depending on how the content evaluation pallet (when included) views it.

**Suggested Solution**

Change `impl` block for default on Status enum to Accepted and check `create_review` and `create_project` for compliance. 

**Additional Information**

* This might break the ad-hoc rewarding logic for reviews since it depends on switching status to "accepted". A fix for that could be to leave the current status enum as is and have the switch be done automatically by the content evaluation pallet on passing, or just leave the rewarding aspect alone to be done by the content evaluation pallet by tweaking `accept_review`. 

> The main goal of the pr is to ensure that no content posted is stuck in `proposed` for a long period of time without any action being done on it.

**Comment by islami00** [comment]
Note: This also means that the current genesis config doesn't have to worry about state of reviews/projects, so it can be simplified further.

**Comment by Immanuel-john** [comment]
> Note: This also means that the current genesis config doesn't have to worry about state of reviews/projects, so it can be simplified further.

Hi. I would like to contribute to this issue. can I?

**Comment by islami00** [comment]
Hi @Immanuel-john , you're welcome to contribute to this issue!

Though this description of the issue is a bit outdated as I've moved the pallets over to the [parachain repo](https://github.com/chocolatenetwork/chocolate-parachain).

The most relevant issue on that repo to this one would be https://github.com/chocolatenetwork/chocolate-parachain/issues/19

Thanks!
